name = "private-folio5"
compatibility_date = "2024-04-01"
main = ".vercel/output/static/_worker.js/index.js"
assets = { directory = ".vercel/output/static" }

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "0f0b63bf-62c4-45b0-980a-5c44833768ad" # Will be filled by user during deployment
